name = "ParallelDataTransfer"
uuid = "2dcacdae-9679-587a-88bb-8b444fb7085b"
authors = ["SciML"]
version = "1.0.0"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
